name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: cv_4.tex

#       - uses: actions/checkout@master
      - name: Commit files
        run: |
          git config --local user.email "safoex@hotmail.com"
          git config --local user.name "GitHub Action"
          git add out/cv_4.pdf
          git commit -m "Add changes" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
