name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: cv_4.tex

#       - uses: actions/checkout@master
      - name: Commit files
        run: |
          git config --local user.email "safoex@hotmail.com"
          git config --local user.name "GitHub Action"
          git add cv_4.pdf
          git commit -m "Add changes" 
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare for pushing to website
        run: |
          mkdir __to_push
          cd __to_push
          mkdir files
          cp ../cv_4.pdf files/cv.pdf
      - name: Push to website
        uses: safoex/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
            source-directory: '__to_push'
            destination-github-username: 'safoex'
            destination-repository-name: 'safoex.github.io'
            git-user-email: safoex@hotmail.com
            reset-or-modify: nonsense
